# version : '3.8'


services:
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/userdb
    depends_on:
      - mongo

  task-service:
    build: ./task-service
    ports:
      - "3001:3001"
    container_name: task-service
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: {}